/**
 * Writes typed ABIs (`as const`, for viem inference) and known public deployments into the SDK:
 *   packages/sdk/src/generated/abis.ts
 *   packages/sdk/src/generated/deployments.ts   (fuji / avalanche only — localhost changes every run)
 * Usage: pnpm --filter @hush/contracts export   (run after `compile` and after each public deploy)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { CONTRACTS_DIR, REPO_ROOT } from "./lib/env.mjs";
import { type HushDeployment, STOCKS } from "./lib/types.js";

const OUT_DIR = path.join(REPO_ROOT, "packages", "sdk", "src", "generated");
const ARTIFACTS: Record<string, string> = {
  encryptedErcAbi: "contracts/eerc/EncryptedERC.sol/EncryptedERC.json",
  registrarAbi: "contracts/eerc/Registrar.sol/Registrar.json",
  hushRegistryAbi: "contracts/hush/HushRegistry.sol/HushRegistry.json",
  hushLedgerAbi: "contracts/hush/HushLedger.sol/HushLedger.json",
  mockUsdcAbi: "contracts/token/MockUSDC.sol/MockUSDC.json",
  mockStockAbi: "contracts/stocks/MockStock.sol/MockStock.json",
  mockStockOracleAbi: "contracts/stocks/MockStockOracle.sol/MockStockOracle.json",
};

const header = "// AUTO-GENERATED by packages/contracts/scripts/export-abis.mts — do not edit.\n";
mkdirSync(OUT_DIR, { recursive: true });

let abis = header;
for (const [name, rel] of Object.entries(ARTIFACTS)) {
  const file = path.join(CONTRACTS_DIR, "artifacts", rel);
  if (!existsSync(file)) throw new Error(`Missing ${file} — run \`pnpm compile\` first`);
  const { abi } = JSON.parse(readFileSync(file, "utf8")) as { abi: unknown[] };
  abis += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(path.join(OUT_DIR, "abis.ts"), abis);

const deployments: Record<number, unknown> = {};
for (const network of ["fuji", "avalanche"]) {
  const file = path.join(CONTRACTS_DIR, "deployments", `${network}.json`);
  if (!existsSync(file)) continue;
  const d = JSON.parse(readFileSync(file, "utf8")) as HushDeployment;
  deployments[d.chainId] = {
    chainId: d.chainId,
    eercDecimals: d.eercDecimals,
    startBlock: d.contracts.EncryptedERC.blockNumber,
    encryptedErc: d.contracts.EncryptedERC.address,
    registrar: d.contracts.Registrar.address,
    usdc: d.contracts.MockUSDC.address,
    hushRegistry: d.contracts.HushRegistry.address,
    hushLedger: d.contracts.HushLedger.address,
    ...(d.contracts.MockStockOracle && {
      stockOracle: d.contracts.MockStockOracle.address,
      stocks: Object.fromEntries(STOCKS.flatMap((s) => (d.contracts[s.symbol] ? [[s.ticker, d.contracts[s.symbol]!.address]] : []))),
    }),
  };
}
writeFileSync(
  path.join(OUT_DIR, "deployments.ts"),
  `${header}import type { HushContracts } from "../types.js";\n\n` +
    `/** Public Hush deployments by chainId. */\nexport const HUSH_DEPLOYMENTS: Record<number, HushContracts> = ${JSON.stringify(deployments, null, 2)};\n`,
);

console.log(`Wrote ${Object.keys(ARTIFACTS).length} ABIs and ${Object.keys(deployments).length} public deployment(s) to ${OUT_DIR}`);
